### ISSUE TITLE
文章重复及文章删除

### ISSUE THREAD

**Issue by hzbdesigner** [hzbdesigner/fsbug#1]
问题1： 文章重复
问题2：删除其中一篇文章，无任何变化
截图如下

**Comment by hzbdesigner** [comment]
![image](https://cloud.githubusercontent.com/assets/1606537/6367780/5b6a79c0-bd11-11e4-82b6-ac6aa55e5721.png)

**Comment by 31858658** [comment]
问题1：查找中
问题2：删除功能已处理好

**Comment by 31858658** [comment]
重复可以因为链接及后期需求调整问题，继续跟进
