### ISSUE TITLE
字体延迟加载

### ISSUE THREAD

**Issue by hzbdesigner** [hzbdesigner/fsbug#10]
![image](https://cloud.githubusercontent.com/assets/1606537/6371597/5199fa66-bd38-11e4-9a04-eb4645f429ff.png)

改字体较大，将近1M，页面正常打开后，加载本字体，已提高网页加载速度。

**Comment by 31858658** [comment]
已解决，使用 jquery 插件lazyload
地址：https://github.com/rgrove/lazyload/

**Comment by hzbdesigner** [comment]
似乎，只有主页和公司简介两个页面做了处理~其他两个页面没有延迟加载的效果。。。
